# Generated by Django 2.2.12 on 2022-11-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_produk'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=100)),
                ('nama_barang', models.CharField(max_length=120)),
                ('harga', models.IntegerField()),
            ],
        ),
    ]
